name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  common:
    path: ../common


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  code_style:
    path: ../code_style

