name: common
description: A common mofule that every other module can access to. 

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies: 
  dio: ^4.0.6

dev_dependencies:
  code_style:
    path: ../code_style
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

